export const ROLES = {
  SALES_EXECUTIVE: 'Sales Executive',
  TEAM_LEADER: 'Team Leader',
  SALES_MANAGER: 'Sales Manager',
  ACCOUNTS_FINANCE: 'Finance Department',
  RTO_DEPARTMENT: 'RTO Department',
  INSURANCE_DEPARTMENT: 'Insurance Department',
  ACCESSORIES_DEPARTMENT: 'Accessories Department',
  FINANCE_DEPARTMENT: 'Banking & Loans',
  PDI_WORKSHOP: 'PDI Workshop',
  BRAND_CEO: 'Brand CEO',
  GROUP_CEO: 'Group CEO',
  DEALER_PRINCIPAL: 'Dealer Principal (Owner)',
  EV_SALES_MANAGER: 'EV Sales Manager',
};

export const ROLE_CONFIGS = {
  [ROLES.SALES_EXECUTIVE]: [
    { label: 'Dashboard', path: '/dashboard', icon: 'LayoutDashboard' },
  ],
  [ROLES.TEAM_LEADER]: [
    { label: 'Dashboard', path: '/dashboard', icon: 'LayoutDashboard' },
    { label: 'Reports', path: '/reports', icon: 'BarChart' },
    { label: 'Deal Sheet', path: '/dashboard?view=dealsheet', icon: 'FileSpreadsheet' },
    { label: 'Team', path: '/team', icon: 'Users' },
  ],
  [ROLES.SALES_MANAGER]: [
    { label: 'Dashboard', path: '/dashboard', icon: 'LayoutDashboard' },
    { label: 'Reports', path: '/reports', icon: 'BarChart3' },
  ],
  [ROLES.ACCOUNTS_FINANCE]: [
    { label: 'Salesleads', path: '/salesleads', icon: 'Briefcase' },
    { label: 'Finance Report', path: '/sales-report', icon: 'FileText' },
  ],
  [ROLES.RTO_DEPARTMENT]: [
    { label: 'Dashboard', path: '/dashboard', icon: 'LayoutDashboard' },
    { label: 'RTO Workspace', path: '/rto-workspace', icon: 'ClipboardList' },
    { label: 'Tax & Challans', path: '/taxes', icon: 'FileWarning' },
    { label: 'HSRP Tracker', path: '/hsrp', icon: 'Truck' },
    { label: 'Document Vault', path: '/vault', icon: 'ShieldCheck' },
  ],
  [ROLES.INSURANCE_DEPARTMENT]: [
    { label: 'Dashboard', path: '/dashboard', icon: 'LayoutDashboard' },
    { label: 'Policy Issuance', path: '/policies', icon: 'FileEdit' },
    { label: 'Premium Calculator', path: '/calculator', icon: 'Calculator' },
    { label: 'Renewals', path: '/renewals', icon: 'RefreshCw' },
    { label: 'Claims Desk', path: '/claims', icon: 'LifeBuoy' },
  ],
  [ROLES.ACCESSORIES_DEPARTMENT]: [
    { label: 'Dashboard', path: '/dashboard', icon: 'LayoutDashboard' },
    { label: 'Fitment Queue', path: '/fitment', icon: 'Tool' },
    { label: 'Inventory Stock', path: '/inventory', icon: 'Box' },
    { label: 'Combo Packages', path: '/packages', icon: 'Layers' },
    { label: 'Stock Procurement', path: '/procurement', icon: 'ShoppingCart' },
  ],
  [ROLES.FINANCE_DEPARTMENT]: [
    { label: 'Dashboard', path: '/dashboard', icon: 'LayoutDashboard' },
    { label: 'Loan Applications', path: '/loans', icon: 'HandCoins' },
    { label: 'Bank Schemes', path: '/schemes', icon: 'Building2' },
    { label: 'Payout Tracker', path: '/payouts', icon: 'History' },
    { label: 'NOC & Closure', path: '/closures', icon: 'FileCheck' },
  ],
  [ROLES.PDI_WORKSHOP]: [
    { label: 'Dashboard', path: '/dashboard', icon: 'LayoutDashboard' },
    { label: 'Inspection Queue', path: '/inspection', icon: 'ClipboardCheck' },
    { label: '100-Point Checklist', path: '/checklist', icon: 'ListChecks' },
    { label: 'Rectification Log', path: '/rectification', icon: 'AlertTriangle' },
    { label: 'Ready for Delivery', path: '/ready', icon: 'CheckCircle2' },
  ],
  [ROLES.BRAND_CEO]: [
    { label: 'Dashboard', path: '/dashboard', icon: 'LayoutDashboard' },
    { label: 'Executive Summary', path: '/summary', icon: 'PieChart' },
    { label: 'Inventory Valuation', path: '/valuation', icon: 'BadgeDollarSign' },
    { label: 'Department Throughput', path: '/throughput', icon: 'Activity' },
    { label: 'Marketing & ROI', path: '/marketing', icon: 'Megaphone' },
    { label: 'Audit Logs', path: '/audits', icon: 'ShieldAlert' },
  ],
  [ROLES.GROUP_CEO]: [
    { label: 'Dashboard', path: '/dashboard', icon: 'LayoutDashboard' },
    { label: 'Group Consolidated View', path: '/consolidated', icon: 'Globe' },
    { label: 'Inter-Brand Analytics', path: '/analytics', icon: 'Network' },
    { label: 'Group Fund Flow', path: '/funds', icon: 'ArrowRightLeft' },
    { label: 'HR & Payroll', path: '/hr', icon: 'UserCog' },
    { label: 'Risk & Compliance', path: '/compliance', icon: 'GanttChart' },
  ],
  [ROLES.DEALER_PRINCIPAL]: [
    { label: 'Dashboard', path: '/dashboard', icon: 'LayoutDashboard' },
    { label: 'CEO Command Center', path: '/command-center', icon: 'Cpu' },
    { label: 'Profitability Analytics', path: '/profitability', icon: 'LineChart' },
    { label: 'Delivery Funnel', path: '/funnel', icon: 'Filter' },
    { label: 'Discount Approvals', path: '/approvals', icon: 'Stamp' },
    { label: 'Customer Satisfaction', path: '/csat', icon: 'SmilePlus' },
  ],
  [ROLES.EV_SALES_MANAGER]: [
    { label: 'EV Dashboard', path: '/dashboard', icon: 'Zap' },
    { label: 'Deal Sheet', path: '/dashboard?view=dealsheet', icon: 'FileSpreadsheet' },
    { label: 'Charging Station', path: '/charging', icon: 'BatteryCharging' },
    { label: 'Team', path: '/team', icon: 'Users' },
    { label: 'Targets', path: '/targets', icon: 'Target' },
    { label: 'Reports', path: '/reports', icon: 'BarChart3' },
  ],
};
